config/routes.rb
Trucklub::Application.routes.draw do
  root :to => 'welcome#index'
  resources :trucks, :only => [:index, :show]
  resources :users, :only => [:new, :create] do
    collection do
      get :admin
    end
    member do
      get :send_code
    end
  end
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/sms' => 'sms#receive'

  # resources :eaters, :only => [:new, :create] do
  #   member do
  #     post :code
  #   end
  # end
  post '/eaters/:id/code' => 'eaters#create_code'
end

app/models/eater.rb
# == Schema Information
#
# Table name: eaters
#
#  id         :integer          not null, primary key
#  location   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Eater < ActiveRecord::Base
  attr_accessible :location
  has_one :user, :as => :userable
  has_many :meals
  validates :location, :presence => true


  def meal_count
    self.meals.count.to_s
  end

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id             :integer          not null, primary key
#  location_date  :date
#  arrival_time   :time
#  departure_time :time
#  address        :string(255)
#  latitude       :float
#  longitude      :float
#  truck_id       :integer
#  secret_code    :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

require 'random-word'
class Location < ActiveRecord::Base
  attr_accessible :location_date, :arrival_time, :departure_time, :address
  belongs_to :truck, :inverse_of => :locations
  before_save :geocode, :generate_secret
  #validates :truck_id, :presence => true

  def send_code_text
    current_date = Date.current
    client = Twilio::REST::Client.new(ENV['TW_SID'], ENV['TW_TOK'])
    client.account.sms.messages.create(:from => '+19177253039', :to => self.truck.phone, :body => "Your trucKlub code for #{current_date} is '#{self.secret_code}'. Reply with your address to be added to our map.")
  end

  private
  def geocode
    result = Geocoder.search(self.address).first

    if result.present?
      self.latitude = result.latitude
      self.longitude = result.longitude
    end
  end

  def generate_secret
    # no words < 3 or > than 7 ot words with underscores
    RandomWord.exclude_list << /_/ << /^.{0,3}$/ << /^.{8,100}$/ << /poison/
    if self.secret_code.blank?
      self.secret_code = RandomWord.nouns.first
    end
  end


end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :integer          not null, primary key
#  meal_date  :date
#  meal_time  :time
#  eater_id   :integer
#  truck_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Meal < ActiveRecord::Base
  attr_accessible :meal_date, :meal_time, :eater_id, :truck_id
  belongs_to :truck, :inverse_of => :meals
  has_one :eater
  # validates :meal_date, :meal_time, :presence => true

  before_save :meal_timestamp
  private
  def meal_timestamp
    self.meal_date = Date.current
    self.meal_time = Time.now
  end
end

app/models/truck.rb
# == Schema Information
#
# Table name: trucks
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  about       :text
#  description :text
#  twitter     :string(255)
#  phone       :string(255)
#  image_url   :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Truck < ActiveRecord::Base
  attr_accessible :title, :description, :twitter, :phone, :image_url, :about
  has_one :user, :as => :userable
  has_many :locations, :inverse_of => :truck
  has_many :meals, :inverse_of => :truck
  validates :title, :description, :twitter, :phone, :presence => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  userable_id     :integer
#  userable_type   :string(255)
#  is_admin        :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  belongs_to :userable, :polymorphic => true
  validates :name, :email, :presence => true

  def is_truck?
    self.userable if self.userable.is_a?(Truck)
  end

  def is_eater?
    self.userable if self.userable.is_a?(Eater)
  end

end

app/models/welcome.rb
class Welcome


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
end

app/controllers/eaters_controller.rb
class EatersController < ApplicationController
  def create_code
    user_code = params[:code]
    todays_locations = Location.where("created_at >= ?", Time.zone.now.beginning_of_day)
    secret_codes = todays_locations.map(&:secret_code)
    if user_code.in?secret_codes
      eater = Eater.find(params[:id])
      meal = Meal.create
      location = Location.where(:secret_code => user_code).first
      meal.truck_id = location.truck_id
      eater.meals << meal
      render :create_code
    else
      render :error
    end
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @auth = User.where(:email => params[:email]).first
    if @auth.present? && @auth.authenticate(params[:password])
      session[:user_id] = @auth.id
      if @auth.is_eater?
        redirect_to trucks_path
      elsif @auth.is_truck?
        truck = Truck.find(@auth.userable.id)
        redirect_to(truck)
      else
        redirect_to(admin_users_path)
      end
    else
      session[:user_id] = nil
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def receive
    message_body = params["Body"]
    from_number = params["From"]
    t1 = Truck.where(:phone => from_number).first
    l1 = t1.locations.last
    l1.address = message_body
    l1.save
    render :nothing => true
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  def index
    @trucks = Truck.all
    @locations = Location.all
  end
  def show
    @truck = Truck.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    location = params[:location]
    if location.present?
      user = User.create(params[:user])
      eater = Eater.create(:location => params[:location])
      eater.user = user
      eater.save
    end
    redirect_to trucks_path
  end

  def admin
    @trucks = Truck.all
  end

  def send_code
    truck = Truck.find(params[:id])
    location = Location.create
    truck.locations << location
    location.send_code_text
    redirect_to admin_users_path
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  # def sms_test
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    if @auth.present?
      "<li>#{link_to('Logout', '/login', :method => :delete, :class => 'button')}</li>"
    else
      "<li>#{link_to('Login to LunchyPunchy', login_path)}</li>"
    end
  end

  def code_form
    "<li class='divider'></li>"
    "<li><a href='#' class='button prefix show_code_button'>Enter Code</a></li>"
    "<li class='divider'></li>"
    "<li><input class = 'hide code_form' type='text' placeholder='Meal code'></li>"
    "<li><a href='#' class='hide button radius success prefix create_code_button'>Submit Code</a></li>"
    "<li><p class='error_code hide'>invalid</p></li>"
  end
end

app/views/eaters/create_code.js.erb
add_to_mealcount();
fill_card();
is_card_full();
$('#sendcodeModal').foundation('reveal', 'close');

app/views/eaters/error.js.erb
$('.error_code').removeClass('hide');
$('#sendcodeModal').foundation('reveal', 'close');

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; 3 Burritos Enterprises</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!-- End Footer -->

app/views/layouts/_nav.html.erb
<div class='fixed'>
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <a href="/">
            LunchyPunchy
          </a>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="left">
        <li class="divider"></li>
        <li><%= link_to('See our trucks', trucks_path) %></li>
        <li class="divider"></li>
        <% if (@auth.present? && @auth.is_eater?) %>
        <li><%= link_to_function "My Loyalty Card", 'show_card();', :class => "button radius" %></li>
        <li class="divider"></li>
        <li><a href="#" class="button radius prefix show_code_button">Enter Code</a></li>
        <% end %>
      </ul>

      <ul class="right">
        <li class="divider"></li>
        <%== login_nav %>
        <li class="divider"></li>
        <% if !@auth %>
        <li><%= link_to('Register', new_user_path, :class => 'button') %></li>
        <li class="divider"></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>
  <!-- End Top Bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchyPunchy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE']}&sensor=false" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" />

</head>
<body>

<%= render :partial => 'layouts/nav' %>
<p class="error_code hide">Invalid code entered. Try again.</p>
<%= render(:partial => 'users/card') if (@auth.present? && @auth.is_eater?)%>
<%= render(:partial => 'users/cardmax') if (@auth.present? && @auth.is_eater?) %>
<%= render(:partial => 'users/sendcode') if (@auth.present? && @auth.is_eater?) %>
<div class="row">


<%= yield %>


</div>




<script>
  $('#card').hide();
  $(document).foundation();
  function show_card(){
    $('#card').fadeToggle();
  }
  $.backstretch("https://dl.dropbox.com/u/5433755/lunchypunchy/lunchypunchy_lg.png");
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39219247-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/session/new.html.haml
.row
  .large-12.columns.spacer
.row
  .large-4.small-10.large-centered.small-centered.columns.content_box
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Get Truckin', :class => 'button small success radius'
      = link_to 'Cancel', root_path, :class => 'button small alert radius'

app/views/trucks/_form.html.haml
.row
  .large-12.columns.spacer
.row
  .large-4.small-10.large-centered.small-centered.columns
    / = form_for @truck, :url => trucks_path, :remote => true do |f|
    /   = f.label :title
    /   = f.text_field :title, :autofocus => true
    /   = f.label :description
    /   = f.text_field :description
    /   = f.label :twitter
    /   = f.text_field :twitter
    /   = f.label :phone
    /   = f.text_field :phone
    /   = f.label :image_url
    /   = f.text_field :image_url
    /   = f.submit nil, :class => 'button small success'
    /   = link_to 'Cancel', root_path, :class => 'button small alert'

app/views/trucks/index.html.haml
.row
  .large-12.columns.small-12.spacer
.row
  .content_box.large-10.large-centered.small-10.small-centered.columns
    .row
      .large-10.small-10.small-centered.columns
        %h1 Our hand-picked selection of <br>premium food trucks:
    %script
      var trucks = [];

    .row
      .large-10.large-centered.small-8.small-centered.columns
        - @locations.each do |location|
          %script
            ="trucks.push({title:'#{location.truck.title}',latitude:#{location.latitude}, longitude:#{location.longitude}});"
          #truck_each.truck_box
            %h3.inline-block.bottom_up= link_to(location.truck.title, "/trucks/" + location.truck.id.to_s)
            %p.orange.bottom_up.bold= location.truck.description
            %p.bold= link_to("@" + location.truck.twitter, "http://twitter.com/" + location.truck.twitter)
            / %p.tiny_address= "Currently at: " + location.address
      .clear
    .row
      .large-12.columns.spacer
    #map_canvas.large-6.large-centered

app/views/trucks/show.html.haml
.row
  .large-12.columns.spacer
.row
  .content_box.large-6.large-centered.small-10.small-centered.columns
    .row
      .large-12.large-centered.small-12.small-centered.columns
        %h1= @truck.title
    .row
      .large-12.large-centered.small-12.small-centered.columns
        .truck_image= image_tag(@truck.image_url)
    .row
      .large-12.large-centered.small-12.small-centered.columns
        %h3.orange= "Serves: " + @truck.description
        %h4= link_to("Go to @" + @truck.twitter, "http://twitter.com/" + @truck.twitter)
        %h5= link_to(number_to_phone(@truck.phone), "tel:#{@truck.phone}")
        - if (@auth.present? && @auth.is_truck? && (@auth.userable.title == @truck.title))
          %p= "Today's code is: #{@auth.userable.locations.last.secret_code}"
        %p= @truck.about

app/views/users/_card.html.haml
- if @auth
  %script
    = "var meal_count = #{@auth.userable.meal_count if (@auth.present? && @auth.is_eater?)}"

.row
  #card.large-6.large-centered.small-8.small-centered.columns
    <br>
    - if (@auth.present? && @auth.is_eater?)
      %h2.cardtext.center=  @auth.name +  "'s LunchyPunchy"

    <br>
    #boxes.large-12.large-centered.small-10.small-centered.columns
      .box
        1
      .box
        2
      .box
        3
      .box
        4
      .box
        5
      .box
        6
      .box
        7
      .box
        8
      .box
        9
%script
  fill_card();

app/views/users/_cardmax.html.haml
#myModal.reveal-modal.transparent.small
  %h1.huge.white.pull_up FREE
  #fist= image_tag("https://dl.dropbox.com/u/5433755/lunchypunchy/fist.png")
  %h1.huge.white.pull_down MEAL!
  %a.close-reveal-modal x

app/views/users/_form.html.haml
.row
  .large-12.columns.spacer
.row
  .large-4.small-10.large-centered.small-centered.columns.content_box
    / = render(:partial => 'shared/errors', :locals => {:object => @user})
    = form_for @user do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = label_tag :location
      = text_field_tag :location
      = f.submit nil, :class => 'button small success'
      = link_to 'Cancel', root_path, :class => 'button small alert'

app/views/users/_sendcode.html.haml
#sendcodeModal.reveal-modal.small
  .row
    .large-12.large-centered.small-12.small-centered
      %h2 Please enter the code you received from the truck:
      = form_tag "/eaters/#{@auth.userable.id}/code", :remote => true do
        = label_tag ' '
        = text_field_tag 'code', nil, :autofocus => true
        = submit_tag 'Submit code', :class => 'right button success prefix create_code_button'
  %a.close-reveal-modal x

app/views/users/admin.html.haml
.row
  .large-12.columns.spacer

- if (@auth.present? && @auth.is_admin == true)
  %h1 Administrator Dashboard:
  / .large-10.large-centered.small-10.small-centered
  - @trucks.each do |truck|
    #truck_each.truck_box
      %h3.inline.block.bottom_up= truck.title
      %p.orange.bottom_up= truck.phone
      %p.round.secondary.label= link_to('Send Code', send_code_user_path(truck.id))

app/views/users/new.html.haml
= render :partial => 'users/form'

app/views/welcome/sms_test.html.haml
.row
  .large-3.columns
    %h1 Test sms

    = form_tag("/sms", :method => "post") do
      = label_tag :from
      = text_field_tag :from
      = label_tag :body
      = text_field_tag :body
      = submit_tag "Enter"
  .large-9.columns